<?xml version="1.0" encoding="utf-8"?><Database Name="Ludus-db" Class="LudusDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=bjvosfs992.database.windows.net;Initial Catalog=Ludus-db;Integrated Security=False;User ID=ludususer;Connect Timeout=15;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="Models.Properties.Settings" SettingsPropertyName="Ludus_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserProfile" Member="UserProfiles">
    <Type Name="UserProfile">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EMailAddress" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="InstitutionUserId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="UserProfile_Student" Member="Students" ThisKey="UserId" OtherKey="UserId" Type="Student" />
      <Association Name="UserProfile_Faculty" Member="Faculties" ThisKey="UserId" OtherKey="UserId" Type="Faculty" />
      <Association Name="UserProfile_PersonalItem" Member="PersonalItems" ThisKey="UserId" OtherKey="UserId" Type="PersonalItem" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SessionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Student_Enrollment" Member="Enrollments" ThisKey="Id" OtherKey="StudentId" Type="Enrollment" />
      <Association Name="UserProfile_Student" Member="UserProfile" ThisKey="UserId" OtherKey="UserId" Type="UserProfile" IsForeignKey="true" />
      <Association Name="Session_Student" Member="Session" ThisKey="SessionId" OtherKey="Id" Type="Session" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Faculty" Member="Faculties">
    <Type Name="Faculty">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SessionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UserProfile_Faculty" Member="UserProfile" ThisKey="UserId" OtherKey="UserId" Type="UserProfile" IsForeignKey="true" />
      <Association Name="Session_Faculty" Member="Session" ThisKey="SessionId" OtherKey="Id" Type="Session" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Assignment" Member="Assignments">
    <Type Name="Assignment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Due" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SubmissionLimit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaximumGrade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Assignment_Submission" Member="Submissions" ThisKey="Id" OtherKey="AssignmentId" Type="Submission" />
      <Association Name="Section_Assignment" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Course_Section" Member="Sections" ThisKey="Id" OtherKey="CourseId" Type="Section" />
    </Type>
  </Table>
  <Table Name="dbo.Enrollment" Member="Enrollments">
    <Type Name="Enrollment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StudentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SectionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Enrollment_Submission" Member="Submissions" ThisKey="Id" OtherKey="EnrollmentId" Type="Submission" />
      <Association Name="Student_Enrollment" Member="Student" ThisKey="StudentId" OtherKey="Id" Type="Student" IsForeignKey="true" />
      <Association Name="Section_Enrollment" Member="Section" ThisKey="SectionId" OtherKey="Id" Type="Section" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Section" Member="Sections">
    <Type Name="Section">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SessionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Limit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Section_Assignment" Member="Assignments" ThisKey="Id" OtherKey="SectionId" Type="Assignment" />
      <Association Name="Section_Enrollment" Member="Enrollments" ThisKey="Id" OtherKey="SectionId" Type="Enrollment" />
      <Association Name="Course_Section" Member="Course" ThisKey="CourseId" OtherKey="Id" Type="Course" IsForeignKey="true" />
      <Association Name="Session_Section" Member="Session" ThisKey="SessionId" OtherKey="Id" Type="Session" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Session" Member="Sessions">
    <Type Name="Session">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Session_Student" Member="Students" ThisKey="Id" OtherKey="SessionId" Type="Student" />
      <Association Name="Session_Faculty" Member="Faculties" ThisKey="Id" OtherKey="SessionId" Type="Faculty" />
      <Association Name="Session_Section" Member="Sections" ThisKey="Id" OtherKey="SessionId" Type="Section" />
    </Type>
  </Table>
  <Table Name="dbo.Submission" Member="Submissions">
    <Type Name="Submission">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EnrollmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubmitterComments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ScorerComments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SubmissionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Assignment_Submission" Member="Assignment" ThisKey="AssignmentId" OtherKey="Id" Type="Assignment" IsForeignKey="true" />
      <Association Name="Enrollment_Submission" Member="Enrollment" ThisKey="EnrollmentId" OtherKey="Id" Type="Enrollment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PersonalItem" Member="PersonalItems">
    <Type Name="PersonalItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllDay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShortDescription" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Complete" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UserProfile_PersonalItem" Member="UserProfile" ThisKey="UserId" OtherKey="UserId" Type="UserProfile" IsForeignKey="true" />
    </Type>
  </Table>
</Database>